# -*- coding: utf-8 -*-
"""ProcesoETL-Essalud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11ZNpN12CdrFYZRRx0ldtFrHevBvCdbu8
"""

import pandas as pd
from datetime import datetime

archivo_txt = 'unidad_01_essalud.txt'
# Leer archivo txt
df = pd.read_csv(archivo_txt, delimiter='|',dtype=str)

# 0. ELIMINAR DUPLICADOS
df = df.drop_duplicates()

# 1. Marca y modelo vacíos → "Nacional"
df['marca'] = df['marca'].fillna('').str.strip()
df['modelo'] = df['modelo'].fillna('').str.strip()
df.loc[df['marca'] == '', 'marca'] = 'Nacional'
df.loc[df['modelo'] == '', 'modelo'] = 'Nacional'

# 2. Unidad → valor estándar "unidad 1"
df['unidad'] = 'Unidad 1'

# 3. Normalizar entrega
def normalizar_entrega(valor):
    valor = valor.upper()

    if '3' in valor or 'TRES' in valor:
        return 'Abastecimiento 3'

    if '1' in valor or 'UNO' in valor:
        return 'Abastecimiento 1'

df['entrega'] = df['entrega'].apply(normalizar_entrega)

# 4. Normalizar fecha (DD/MM/YYYY)
def normalizar_fecha(fecha):
    if pd.isna(fecha) or fecha.strip() == '':
        return None

    for fmt in ('%d-%m-%Y', '%d/%m/%Y', '%d/%m/%y'):
        try:
            return datetime.strptime(fecha.strip(), fmt).strftime('%d/%m/%Y')
        except ValueError:
            continue

    return None

df['fecha_recepcion'] = df['fecha_recepcion'].apply(normalizar_fecha)

# Fecha por defecto (moda)
fecha_defecto = (
    df['fecha_recepcion']
    .dropna()
    .mode()
)

fecha_defecto = fecha_defecto.iloc[0] if not fecha_defecto.empty else None

df['fecha_recepcion'] = df['fecha_recepcion'].fillna(fecha_defecto)

# 5. Normalizar estado → Completo / Dañado
def normalizar_estado(valor):
    if pd.isna(valor):
        return 'Pendiente'

    valor = str(valor).upper()

    if 'DANIADO' in valor or 'DAÑADO' in valor:
        return 'Dañado'

    if 'PENDIENTE' in valor:
        return 'Pendiente'

    if 'COMPLETO' in valor:
        return 'Completo'

df['estado'] = df['estado'].apply(normalizar_estado)

# 6. Title Case en columnas específicas
columnas_title = ['denominacion', 'marca', 'modelo']

for col in columnas_title:
    df[col] = (df[col].fillna('').str.strip().str.lower().str.title())

# Obtener nombre de unidad desde la data
valor_unidad = df['unidad'].dropna().unique()[0]
unidad_archivo = valor_unidad.replace(' ', '_')

archivo_excel = f'Fich_Des_{unidad_archivo}.xlsx'

df.to_excel(archivo_excel, index=False)

print('ETL finalizado correctamente')
print(f'Archivo generado: {archivo_excel}')